package com.example;

public class Images {
	public final static String[] imageUrls = new String[] {
			
			"http://www.sinoace.net/android/coolwar.jpg",
			"http://www.sinoace.net/android/a7_1.jpg",
			"http://www.sinoace.net/android/a7_2.jpg",
			"http://www.sinoace.net/android/a7_3.jpg",
			"http://www.sinoace.net/android/a7_4.jpg",
			"http://www.sinoace.net/android/1942.jpg",
			"http://www.sinoace.net/android/coolwar.jpg",
			"http://www.sinoace.net/android/a7_1.jpg",
			"http://www.sinoace.net/android/a7_2.jpg",
			"http://www.sinoace.net/android/coolwar.jpg",
			"http://www.sinoace.net/android/a7_3.jpg",
			"http://www.sinoace.net/android/a7_4.jpg",
			"http://www.sinoace.net/android/1942.jpg",
			"http://www.sinoace.net/android/a7_1.jpg",
			"http://www.sinoace.net/android/coolwar.jpg",
			"http://www.sinoace.net/android/a7_2.jpg",
			"http://www.sinoace.net/android/a7_3.jpg",
			"http://www.sinoace.net/android/a7_4.jpg",
			"http://www.sinoace.net/android/coolwar.jpg",
			"http://www.sinoace.net/android/1942.jpg",
			"http://www.sinoace.net/android/a7_1.jpg",
			"http://www.sinoace.net/android/a7_2.jpg",
			"http://www.sinoace.net/android/coolwar.jpg",
			"http://www.sinoace.net/android/a7_3.jpg",
			"http://www.sinoace.net/android/a7_4.jpg",
			"http://www.sinoace.net/android/1942.jpg",
			"http://www.sinoace.net/android/a7_1.jpg",
			"http://www.sinoace.net/android/a7_2.jpg",
			"http://www.sinoace.net/android/coolwar.jpg",
			"http://www.sinoace.net/android/a7_3.jpg",
			"http://www.sinoace.net/android/a7_4.jpg",
			"http://www.sinoace.net/android/1942.jpg",
			"http://www.sinoace.net/android/a7_1.jpg",
			"http://www.sinoace.net/android/a7_2.jpg",
			"http://www.sinoace.net/android/coolwar.jpg",
			"http://www.sinoace.net/android/a7_3.jpg",
			"http://www.sinoace.net/android/a7_4.jpg",
			"http://www.sinoace.net/android/1942.jpg",
			"http://www.sinoace.net/android/a7_1.jpg",
			"http://www.sinoace.net/android/a7_2.jpg",
			"http://www.sinoace.net/android/coolwar.jpg",
			"http://www.sinoace.net/android/a7_3.jpg",
			"http://www.sinoace.net/android/a7_4.jpg",
			"http://www.sinoace.net/android/1942.jpg",
			"http://www.sinoace.net/android/a7_1.jpg",
			"http://www.sinoace.net/android/a7_2.jpg",
			"http://www.sinoace.net/android/coolwar.jpg",
			"http://www.sinoace.net/android/a7_3.jpg",
			"http://www.sinoace.net/android/a7_4.jpg",
			"http://www.sinoace.net/android/1942.jpg",
			"http://www.sinoace.net/android/coolwar.jpg",

	};

}
